baseurl: "/dss"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
gems:
  - jekyll-redirect-from
permalink: pretty
title: "Darwin Streaming Server"
url: "https://macosforge.github.io"
